### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by goelaakash79** [dsckiet/dsc-connect-client#17]
- [x] 1. Update the UI for the below section

![image](https://user-images.githubusercontent.com/30005684/80260098-c7056700-86a4-11ea-970f-5af5326be861.png) 

- [x] 2. Add Loading on the click of Login and register buttons

- [x] 3. Bring the search button inline with the input field
![image](https://user-images.githubusercontent.com/30005684/80260287-2e231b80-86a5-11ea-920a-2edd43f56366.png)

- [x] 4. Giver corner radius to login and register modals

- [x] 5. Give bottom space after email field
![image](https://user-images.githubusercontent.com/30005684/80260451-940fa300-86a5-11ea-9eb7-42eb07bb2bd3.png)

- [x] 6. Improve the UI of Confirmation Email
![image](https://user-images.githubusercontent.com/30005684/80260681-0ed8be00-86a6-11ea-9505-4adff15f30b1.png)

- [x] 7. Improve the UI for the below section
![image](https://user-images.githubusercontent.com/30005684/80260709-2152f780-86a6-11ea-958e-4e250d7c7ab1.png)

- [x] 8. Add option to `add a custom domain for the DSC(other than ml, web, etc`. Let the user add up to 3 custom domains.

- [x] 9. Add loading, when the user clicks the Add your community button.

- [x] 10. Show some illustration and better text, while the community is being reviewed + maximum Time required for the review.

**Comment by mayanksh99** [comment]
No 8 is solved as it is already present.

**Comment by mayanksh99** [comment]
Only no 6 remain and check the loading button while login or register it's not working while code is fine

**Comment by goelaakash79** [comment]
Please change the text of the review community section, as mentioned in the above checklist

**Comment by goelaakash79** [comment]
Resolve the issue point 6 ASAP.

**Comment by mayanksh99** [comment]
Working on it.

**Comment by mayanksh99** [comment]
Point 6 resolved.

**Comment by goelaakash79** [comment]
okay
